
/**
 * created by Prakhar Verma
 * 15 November 2017
 */

update country set country_dial_code="93" where country_name="Afghanistan";
update country set country_dial_code="358-8" where country_name="Åland Islands";
update country set country_dial_code="355" where country_name="Albania";
update country set country_dial_code="213" where country_name="Algeria";
update country set country_dial_code="1-684" where country_name="American Samoa";
update country set country_dial_code="376" where country_name="Andorra";
update country set country_dial_code="244" where country_name="Angola";
update country set country_dial_code="1-264" where country_name="Anguilla";
update country set country_dial_code="672" where country_name="Antarctica";
update country set country_dial_code="1-268" where country_name="Antigua & Barbuda";
update country set country_dial_code="54" where country_name="Argentina";
update country set country_dial_code="374" where country_name="Armenia";
update country set country_dial_code="297" where country_name="Aruba";
update country set country_dial_code="247" where country_name="Ascension Island";
update country set country_dial_code="61" where country_name="Australia";
update country set country_dial_code="43" where country_name="Austria";
update country set country_dial_code="994" where country_name="Azerbaijan";
update country set country_dial_code="1-242" where country_name="Bahamas";
update country set country_dial_code="973" where country_name="Bahrain";
update country set country_dial_code="880" where country_name="Bangladesh";
update country set country_dial_code="1-246" where country_name="Barbados";
update country set country_dial_code="375" where country_name="Belarus";
update country set country_dial_code="32" where country_name="Belgium";
update country set country_dial_code="501" where country_name="Belize";
update country set country_dial_code="229" where country_name="Benin";
update country set country_dial_code="1-441" where country_name="Bermuda";
update country set country_dial_code="975" where country_name="Bhutan";
update country set country_dial_code="591" where country_name="Bolivia";
update country set country_dial_code="387" where country_name="Bosnia & Herzegovina";
update country set country_dial_code="267" where country_name="Botswana";
update country set country_dial_code="55" where country_name="Brazil";
update country set country_dial_code="246" where country_name="British Indian Ocean Territory";
update country set country_dial_code="1-284" where country_name="British Virgin Islands";
update country set country_dial_code="673" where country_name="Brunei";
update country set country_dial_code="359" where country_name="Bulgaria";
update country set country_dial_code="226" where country_name="Burkina Faso";
update country set country_dial_code="257" where country_name="Burundi";
update country set country_dial_code="855" where country_name="Cambodia";
update country set country_dial_code="237" where country_name="Cameroon";
update country set country_dial_code="1" where country_name="Canada";
update country set country_dial_code="34" where country_name="Canary Islands";
update country set country_dial_code="238" where country_name="Cape Verde";
update country set country_dial_code="599 3" where country_name="Caribbean Netherlands";
update country set country_dial_code="1-345" where country_name="Cayman Islands";
update country set country_dial_code="236" where country_name="Central African Republic";
update country set country_dial_code="34" where country_name="Ceuta & Melilla";
update country set country_dial_code="235" where country_name="Chad";
update country set country_dial_code="56" where country_name="Chile";
update country set country_dial_code="86" where country_name="China";
update country set country_dial_code="61" where country_name="Christmas Island";
update country set country_dial_code="61 89162" where country_name="Cocos (Keeling) Islands";
update country set country_dial_code="57" where country_name="Colombia";
update country set country_dial_code="269" where country_name="Comoros";
update country set country_dial_code="242" where country_name="Congo - Brazzaville";
update country set country_dial_code="243" where country_name="Congo - Kinshasa";
update country set country_dial_code="682" where country_name="Cook Islands";
update country set country_dial_code="506" where country_name="Costa Rica";
update country set country_dial_code="225" where country_name="Côte d’Ivoire";
update country set country_dial_code="385" where country_name="Croatia";
update country set country_dial_code="53" where country_name="Cuba";
update country set country_dial_code="599" where country_name="Curaçao";
update country set country_dial_code="357" where country_name="Cyprus";
update country set country_dial_code="420" where country_name="Czech Republic";
update country set country_dial_code="45" where country_name="Denmark";
update country set country_dial_code="246" where country_name="Diego Garcia";
update country set country_dial_code="253" where country_name="Djibouti";
update country set country_dial_code="1-767" where country_name="Dominica";
update country set country_dial_code="1-809,1-829,1-849" where country_name="Dominican Republic";
update country set country_dial_code="593" where country_name="Ecuador";
update country set country_dial_code="20" where country_name="Egypt";
update country set country_dial_code="503" where country_name="El Salvador";
update country set country_dial_code="240" where country_name="Equatorial Guinea";
update country set country_dial_code="291" where country_name="Eritrea";
update country set country_dial_code="372" where country_name="Estonia";
update country set country_dial_code="251" where country_name="Ethiopia";
update country set country_dial_code="500" where country_name="Falkland Islands";
update country set country_dial_code="298" where country_name="Faroe Islands";
update country set country_dial_code="679" where country_name="Fiji";
update country set country_dial_code="358" where country_name="Finland";
update country set country_dial_code="33" where country_name="France";
update country set country_dial_code="93" where country_name="French Guiana";
update country set country_dial_code="689" where country_name="French Polynesia";
update country set country_dial_code="93" where country_name="French Southern Territories";
update country set country_dial_code="241" where country_name="Gabon";
update country set country_dial_code="220" where country_name="Gambia";
update country set country_dial_code="995" where country_name="Georgia";
update country set country_dial_code="49" where country_name="Germany";
update country set country_dial_code="233" where country_name="Ghana";
update country set country_dial_code="350" where country_name="Gibraltar";
update country set country_dial_code="30" where country_name="Greece";
update country set country_dial_code="299" where country_name="Greenland";
update country set country_dial_code="1-473" where country_name="Grenada";
update country set country_dial_code="590" where country_name="Guadeloupe";
update country set country_dial_code="1-671" where country_name="Guam";
update country set country_dial_code="502" where country_name="Guatemala";
update country set country_dial_code="44-1481" where country_name="Guernsey";
update country set country_dial_code="224" where country_name="Guinea";
update country set country_dial_code="245" where country_name="Guinea-Bissau";
update country set country_dial_code="592" where country_name="Guyana";
update country set country_dial_code="509" where country_name="Haiti";
update country set country_dial_code="504" where country_name="Honduras";
update country set country_dial_code="852" where country_name="Hong Kong SAR China";
update country set country_dial_code="36" where country_name="Hungary";
update country set country_dial_code="354" where country_name="Iceland";
update country set country_dial_code="91" where country_name="India";
update country set country_dial_code="62" where country_name="Indonesia";
update country set country_dial_code="98" where country_name="Iran";
update country set country_dial_code="964" where country_name="Iraq";
update country set country_dial_code="353" where country_name="Ireland";
update country set country_dial_code="44-1624" where country_name="Isle of Man";
update country set country_dial_code="972" where country_name="Israel";
update country set country_dial_code="39" where country_name="Italy";
update country set country_dial_code="1-876" where country_name="Jamaica";
update country set country_dial_code="81" where country_name="Japan";
update country set country_dial_code="44-1534" where country_name="Jersey";
update country set country_dial_code="962" where country_name="Jordan";
update country set country_dial_code="7" where country_name="Kazakhstan";
update country set country_dial_code="254" where country_name="Kenya";
update country set country_dial_code="686" where country_name="Kiribati";
update country set country_dial_code="383" where country_name="Kosovo";
update country set country_dial_code="965" where country_name="Kuwait";
update country set country_dial_code="996" where country_name="Kyrgyzstan";
update country set country_dial_code="856" where country_name="Laos";
update country set country_dial_code="371" where country_name="Latvia";
update country set country_dial_code="961" where country_name="Lebanon";
update country set country_dial_code="266" where country_name="Lesotho";
update country set country_dial_code="231" where country_name="Liberia";
update country set country_dial_code="218" where country_name="Libya";
update country set country_dial_code="423" where country_name="Liechtenstein";
update country set country_dial_code="370" where country_name="Lithuania";
update country set country_dial_code="352" where country_name="Luxembourg";
update country set country_dial_code="853" where country_name="Macau SAR China";
update country set country_dial_code="389" where country_name="Macedonia";
update country set country_dial_code="261" where country_name="Madagascar";
update country set country_dial_code="265" where country_name="Malawi";
update country set country_dial_code="60" where country_name="Malaysia";
update country set country_dial_code="960" where country_name="Maldives";
update country set country_dial_code="223" where country_name="Mali";
update country set country_dial_code="356" where country_name="Malta";
update country set country_dial_code="692" where country_name="Marshall Islands";
update country set country_dial_code="596" where country_name="Martinique";
update country set country_dial_code="222" where country_name="Mauritania";
update country set country_dial_code="230" where country_name="Mauritius";
update country set country_dial_code="262" where country_name="Mayotte";
update country set country_dial_code="52" where country_name="Mexico";
update country set country_dial_code="691" where country_name="Micronesia";
update country set country_dial_code="373" where country_name="Moldova";
update country set country_dial_code="377" where country_name="Monaco";
update country set country_dial_code="976" where country_name="Mongolia";
update country set country_dial_code="382" where country_name="Montenegro";
update country set country_dial_code="1-664" where country_name="Montserrat";
update country set country_dial_code="212" where country_name="Morocco";
update country set country_dial_code="258" where country_name="Mozambique";
update country set country_dial_code="95" where country_name="Myanmar (Burma)";
update country set country_dial_code="264" where country_name="Namibia";
update country set country_dial_code="674" where country_name="Nauru";
update country set country_dial_code="977" where country_name="Nepal";
update country set country_dial_code="31" where country_name="Netherlands";
update country set country_dial_code="687" where country_name="New Caledonia";
update country set country_dial_code="64" where country_name="New Zealand";
update country set country_dial_code="505" where country_name="Nicaragua";
update country set country_dial_code="227" where country_name="Niger";
update country set country_dial_code="234" where country_name="Nigeria";
update country set country_dial_code="683" where country_name="Niue";
update country set country_dial_code="672 3" where country_name="Norfolk Island";
update country set country_dial_code="850" where country_name="North Korea";
update country set country_dial_code="1-670" where country_name="Northern Mariana Islands";
update country set country_dial_code="47" where country_name="Norway";
update country set country_dial_code="968" where country_name="Oman";
update country set country_dial_code="92" where country_name="Pakistan";
update country set country_dial_code="680" where country_name="Palau";
update country set country_dial_code="93" where country_name="Palestinian Territories";
update country set country_dial_code="507" where country_name="Panama";
update country set country_dial_code="675" where country_name="Papua New Guinea";
update country set country_dial_code="595" where country_name="Paraguay";
update country set country_dial_code="51" where country_name="Peru";
update country set country_dial_code="63" where country_name="Philippines";
update country set country_dial_code="64" where country_name="Pitcairn Islands";
update country set country_dial_code="48" where country_name="Poland";
update country set country_dial_code="351" where country_name="Portugal";
update country set country_dial_code="1-787,1-939" where country_name="Puerto Rico";
update country set country_dial_code="974" where country_name="Qatar";
update country set country_dial_code="262" where country_name="Réunion";
update country set country_dial_code="40" where country_name="Romania";
update country set country_dial_code="7" where country_name="Russia";
update country set country_dial_code="250" where country_name="Rwanda";
update country set country_dial_code="685" where country_name="Samoa";
update country set country_dial_code="378" where country_name="San Marino";
update country set country_dial_code="239" where country_name="São Tomé & Príncipe";
update country set country_dial_code="966" where country_name="Saudi Arabia";
update country set country_dial_code="221" where country_name="Senegal";
update country set country_dial_code="381" where country_name="Serbia";
update country set country_dial_code="248" where country_name="Seychelles";
update country set country_dial_code="232" where country_name="Sierra Leone";
update country set country_dial_code="65" where country_name="Singapore";
update country set country_dial_code="1-721" where country_name="Sint Maarten";
update country set country_dial_code="421" where country_name="Slovakia";
update country set country_dial_code="386" where country_name="Slovenia";
update country set country_dial_code="677" where country_name="Solomon Islands";
update country set country_dial_code="252" where country_name="Somalia";
update country set country_dial_code="27" where country_name="South Africa";
update country set country_dial_code="93" where country_name="South Georgia & South Sandwich Islands";
update country set country_dial_code="82" where country_name="South Korea";
update country set country_dial_code="211" where country_name="South Sudan";
update country set country_dial_code="34" where country_name="Spain";
update country set country_dial_code="94" where country_name="Sri Lanka";
update country set country_dial_code="93" where country_name="St. Barthélemy";
update country set country_dial_code="290" where country_name="St. Helena";
update country set country_dial_code="869" where country_name="St. Kitts & Nevis";
update country set country_dial_code="758" where country_name="St. Lucia";
update country set country_dial_code="721" where country_name="St. Martin";
update country set country_dial_code="508" where country_name="St. Pierre & Miquelon";
update country set country_dial_code="784" where country_name="St. Vincent & Grenadines";
update country set country_dial_code="249" where country_name="Sudan";
update country set country_dial_code="597" where country_name="Suriname";
update country set country_dial_code="47" where country_name="Svalbard & Jan Mayen";
update country set country_dial_code="268" where country_name="Swaziland";
update country set country_dial_code="46" where country_name="Sweden";
update country set country_dial_code="41" where country_name="Switzerland";
update country set country_dial_code="963" where country_name="Syria";
update country set country_dial_code="886" where country_name="Taiwan";
update country set country_dial_code="992" where country_name="Tajikistan";
update country set country_dial_code="255" where country_name="Tanzania";
update country set country_dial_code="66" where country_name="Thailand";
update country set country_dial_code="670" where country_name="Timor-Leste";
update country set country_dial_code="228" where country_name="Togo";
update country set country_dial_code="690" where country_name="Tokelau";
update country set country_dial_code="676" where country_name="Tonga";
update country set country_dial_code="1-868" where country_name="Trinidad & Tobago";
update country set country_dial_code="290" where country_name="Tristan da Cunha";
update country set country_dial_code="216" where country_name="Tunisia";
update country set country_dial_code="90" where country_name="Turkey";
update country set country_dial_code="993" where country_name="Turkmenistan";
update country set country_dial_code="1-649" where country_name="Turks & Caicos Islands";
update country set country_dial_code="688" where country_name="Tuvalu";
update country set country_dial_code="1" where country_name="U.S. Outlying Islands";
update country set country_dial_code="1-340" where country_name="U.S. Virgin Islands";
update country set country_dial_code="256" where country_name="Uganda";
update country set country_dial_code="380" where country_name="Ukraine";
update country set country_dial_code="971" where country_name="United Arab Emirates";
update country set country_dial_code="44" where country_name="United Kingdom";
update country set country_dial_code="1" where country_name="United States";
update country set country_dial_code="598" where country_name="Uruguay";
update country set country_dial_code="998" where country_name="Uzbekistan";
update country set country_dial_code="678" where country_name="Vanuatu";
update country set country_dial_code="379" where country_name="Vatican City";
update country set country_dial_code="58" where country_name="Venezuela";
update country set country_dial_code="84" where country_name="Vietnam";
update country set country_dial_code="681" where country_name="Wallis & Futuna";
update country set country_dial_code="212" where country_name="Western Sahara";
update country set country_dial_code="967" where country_name="Yemen";
update country set country_dial_code="260" where country_name="Zambia";
update country set country_dial_code="263" where country_name="Zimbabwe";

/*
 * --------------------------------------------------------------------------------------------------
 *  Last commit date Wednesday 8 November 2017 
 * -------------------------------------------------------------------------------------------------
 */
